### ISSUE TITLE
64 Bit

### ISSUE THREAD

**Issue by P373R** [Hughp135/angular-5-chat-app#33]
I like this script however the dependencies from Node cannot run under X64 operating systems... is there a workaround for this? I would like to use it, but i am using only 64 bit systems and no, i dont have the resorces to run Virtual systems... Is there any solution to make this work on x64?

**Comment by Hughp135** [comment]
What error message are you getting? It runs on both of my computers (windows and mac) and 64 bit is standard.

**Comment by P373R** [comment]
I figured out, i had to install separately the NPM-SASS module it was missing after npm install... the install itself does not do it, however after i boot up on localhost:4200 there is only just blank screen.

update: it stops at webpack:compiled successfully at around 69%

I am trying to install plus modules but the error message is this:
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.0.1: wanted {"os":"darwin","
arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Hughp135** [comment]
Could try a different version on node, I've had that error before but can't remember how I solved it.

**Comment by P373R** [comment]
What Version you use now?

Update: i installed with older node.js(2018 feb) npm i -f and it went good exept, it requires dependency mongoose@5.3.15 and i cannot install that, my mongodb is up and running at required port, however still: when is start the npm start, it writes:

webpack: compiled succesfuly 

and itis stops, at 127.0.0.1:4500 is only favicon and a blank screen both on opera, ff, chrome and iexplorer

when i try to install mongoose@5.3.15 it writes this:

chat-angular-electron@0.0.0 e:\Discord Clone\angular-5-chat-app-master
`-- UNMET PEER DEPENDENCY mongoose@5.3.14
  +-- kareem@2.3.0
  +-- mongoose-legacy-pluralize@1.0.2
  +-- mpath@0.5.1
  +-- mquery@3.2.0
  | +-- bluebird@3.5.1
  | `-- debug@3.1.0
  `-- sliced@1.0.1

I cannot install becouse it says 
npm WARN mongoose-delete@0.4.0 requires a peer of mongoose@4.x but none was inst
alled.
npm ERR! code 1

i did installed 4.1.0 to have what he wants to uninstall but still it has the same error...

**Comment by Hughp135** [comment]
It works with node 10.11.0 (just tested). Try doing a `rm -rf node_modules` and `rm package-lock.json` and `npm i` again

**Comment by P373R** [comment]
![nope](https://user-images.githubusercontent.com/6048211/49594192-9f114880-f975-11e8-8feb-355637eeec3a.jpg)

This is the situation, but not dropping any other error...

**Comment by Hughp135** [comment]
That happens when the front-end is unable to communicate with the back-end.

I don't see the server running in your terminal windows. Did you do `npm run start:server:dev`? 

If it is running, check that the port is correct (this is taken from default.yml by default)

**Comment by P373R** [comment]
Thank you it is working now. :D
:dagger: Nailed it :D i was notrunning npm run start:server:dev
only the npm start (i thought they was not a separate thing, now i run both and it is working)

thank you very much for your patience!

Also the audio input not working, it says all my devices are unknown device.. :D but the server itslf is works!! (on your pubg test chat server my devices are working well.)

Edit: nevermind it was solved itself somehow, i dont know how...

**Comment by Hughp135** [comment]
Yeah, the audio device names don't always show (I've noticed this more on firefox than chrome), I believe it is due to some browser permissions issue that I have yet to figure out (will look into it more though).
